kind: Deployment
apiVersion: apps/v1
metadata:
  name: dh-gateway
  namespace: dealhunter
  labels:
    app: dh-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dh-gateway
  template:
    metadata:
      labels:
        app: dh-gateway
    spec:
      containers:
        - name: dh-gateway
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/dh-gateway:SNAPSHOT-$BUILD_NUMBER
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  
---
kind: Service
apiVersion: v1
metadata:
  name: dh-gateway
  namespace: dealhunter
  labels:
    app: dh-gateway
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31003
  selector:
    app: dh-gateway
  type: NodePort
  sessionAffinity: None
